logging:
  level:
    org:
      springframework: info

adolin:
  sample:
    service:
      some-info: "init value"

---
spring:
  profiles: test

logging:
  level:
    org:
      springframework: trace